steps:
#executo o test unitario
  - id: "Rodando unit test"
    name: "gcr.io/cloud-builders/go:alpine"
    args: ["go", "test", ".", "-v"]
    env: ['PROJECT_ROOT=desafio-ci']

  # - id: "Build imagem"
  #   name: "gcr.io/cloud-builders/docker"
  #   args: ["build", "-t", "gcr.io/$PROJECT_ID/desafio-ci:latest", "."]


# images: #faz o push da imagem buildada
# - 'gcr.io/$PROJECT_ID/desafio-ci:latest'