steps:
  - id: "Rodando Go unit test"
    name: "gcr.io/cloud-builders/go:alpine"
    args: ["test", ".", "-v"]
    env: ['PROJECT_ROOT=desafio-ci']

  - id: "Build imagem de CI"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/desafio-ci:latest", "-t", "gcr.io/$PROJECT_ID/desafio-ci:1.1.0", "."]

images:
- 'gcr.io/$PROJECT_ID/desafio-ci:latest'
- 'gcr.io/$PROJECT_ID/desafio-ci:1.1.0'